import React from 'react';

export default [
  <option key={0} value={1}>{'A'}</option>,
  <option key={1} value={2}>{'B'}</option>,
  <option key={2} value={3}>{'C'}</option>,
  <option key={3} value={4}>{'D'}</option>,
  <option key={4} value={5}>{'E'}</option>,
  <option key={5} value={6}>{'F'}</option>,
  <option key={6} value={7}>{'G'}</option>,
  <option key={7} value={8}>{'H'}</option>,
  <option key={8} value={9}>{'I'}</option>,
  <option key={9} value={10}>{'J'}</option>,
  <option key={10} value={11}>{'K'}</option>,
  <option key={11} value={12}>{'L'}</option>,
  <option key={12} value={13}>{'M'}</option>,
  <option key={13} value={14}>{'N'}</option>,
  <option key={14} value={15}>{'O'}</option>,
  <option key={15} value={16}>{'P'}</option>,
  <option key={16} value={17}>{'Q'}</option>,
  <option key={17} value={18}>{'R'}</option>,
  <option key={18} value={19}>{'S'}</option>,
  <option key={19} value={20}>{'T'}</option>,
  <option key={20} value={21}>{'U'}</option>,
  <option key={21} value={22}>{'V'}</option>,
  <option key={22} value={23}>{'W'}</option>,
  <option key={23} value={24}>{'X'}</option>,
  <option key={24} value={25}>{'Y'}</option>,
  <option key={25} value={26}>{'Z'}</option>,
]