import React from 'react';

export default [
  <option key={0} value={0}>{'A'}</option>,
  <option key={1} value={1}>{'B'}</option>,
  <option key={2} value={2}>{'C'}</option>,
  <option key={3} value={3}>{'D'}</option>,
  <option key={4} value={4}>{'E'}</option>,
  <option key={5} value={5}>{'F'}</option>,
  <option key={6} value={6}>{'G'}</option>,
  <option key={7} value={7}>{'H'}</option>,
  <option key={8} value={8}>{'I'}</option>,
  <option key={9} value={9}>{'J'}</option>,
  <option key={10} value={10}>{'K'}</option>,
  <option key={11} value={11}>{'L'}</option>,
  <option key={12} value={12}>{'M'}</option>,
  <option key={13} value={13}>{'N'}</option>,
  <option key={14} value={14}>{'O'}</option>,
  <option key={15} value={15}>{'P'}</option>,
  <option key={16} value={16}>{'Q'}</option>,
  <option key={17} value={17}>{'R'}</option>,
  <option key={18} value={18}>{'S'}</option>,
  <option key={19} value={19}>{'T'}</option>,
  <option key={20} value={20}>{'U'}</option>,
  <option key={21} value={21}>{'V'}</option>,
  <option key={22} value={22}>{'W'}</option>,
  <option key={23} value={23}>{'X'}</option>,
  <option key={24} value={24}>{'Y'}</option>,
  <option key={25} value={25}>{'Z'}</option>,
]